import './component/cmp/MaterialIcon.js'
import './component/cmp/ScrollPane.js'
import './component/cmp/SlotManager.js'
import './component/cmp/StyleGlobal.js'
import './component/cmp/StyleFor.js'
import './component/cmp/Input.js'

import './component/prj/Badges.js'
import './component/prj/Badge.js'
import './component/prj/SideBar.js'
import './component/prj/Login.js'
import './component/cmp/Button.js'